spring:
  application:
    #服务名
    name: eureka-server
  profiles:
    active: eureka1
eureka:
  client:
    #是否从Eureka上获取注册信息
    fetch-registry: false
    #是否注册自身到Eureka服务器
    register-with-eureka: false
    serviceUrl:
      #注册中心地址
      defaultZone: http://localhost:8080/eureka
  #关闭自我保护机制，保证不可用服务及时踢出
  server:
    enable-self-preservation: true

