eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route_ws_path
          uri: lb://user-center #此处需要使用lb协议
          predicates:
            - Path=/user-center/messages/info/**

        - id: route-websocket
          uri: lb:ws://user-center
          predicates:
            - Path=/user-center/messages/**

        - id: route_user_center_path
          uri: lb://user-center #此处需要使用lb协议
          predicates:
            - Path=/user-center/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
