eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route_path
          uri: lb://eureka-client #此处需要使用lb协议
          predicates:
            - Path=/admin/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
